# -*- coding: utf-8 -*-
"""workbookUnit3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1la4LvZF4Uaq_BQ7iXsd0YUgv0A5ExrkJ

Juan Miguel V. Recondo

CITCS 1-O

Exit Workbook For Unit 3 in CC2

---
"""

x = 19

if x > 0:
    print("The value of x is positive.")
elif x < 0:
    print("The value of x is negative.")
elif x == 0:
    print("The value of x is zero.")
else:
    print("x is not a number.")

grade = float(input("Enter you grade: "))

if grade >= 90:
    print("You are doing great!")
elif grade >= 80 and grade < 90:
    print("You are doing good!")
elif grade >= 75 and grade < 80:
    print("You can do better!")
else:
    print("There is always next time.")

x = 19

if x > 0:
    print("The value of x is positive.")

    if x % 2 == 0:
        print("x is also an even number.")
    else:
        print("x is also an odd number.")
elif x < 0:
    print("The value of x is negative.")
elif x == 0:
    print("The value of x is zero.")
else:
    print("x is not a number.")

year = int(input("Enter a year: "))

is_leap_year = True
if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
    is_leap_year = True
elif year % 4 != 0 or year % 100 == 0:
    is_leap_year = False

if is_leap_year:
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

code = "C"

match code:
    case "A":
        print("Alpha")
    case "B":
        print("Bravo")
    case "C":
        print("Charlie")
    case _:
        print("Unknown code")

course_code = input("Enter a course code: ")

match course_code:
    case "CIT8":
        print("IT Internship")
    case "CIT6":
        print("Capstone Project 1")
    case "CIT7":
        print("Capstone Project 2")
    case "CC9":
        print("Discrete Structures")
    case "CC12":
        print("Statistical Design and Analysis")
    case _:
        print("Invalid course code")
