# -*- coding: utf-8 -*-
"""Workbook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xeGrOEVE8tQEzRu9JM9kZDXpeq4DLQlK

Juan Miguel V. Recondo

CITCS 1-O

Exit Workbook For Unit 2 in CC2
"""

a = "Hello"
print(a)

an_integer = 5
is_true = True
a_string = "Heya"
a_list = [1, 2, 3]
null_value = None

print(an_integer)
print(is_true)
print(a_string)
print(a_list)
print(null_value)

name = "Juan Miguel"
age = 19
is_enrolled = True
weight = None

print(f"Hello! I am {name}.")
print(f"I am {age} years old.")
print(f"And it is {str(is_enrolled).lower()} that I am enrolled.")
print(f"I don't know my weight, and I don't have a tool to measure it. So let's refer to my weight as {str(weight).lower()} for now.")

my_list = [1, 2, 3, "apple", "banana"]
my_tuple = (1, 2, 3, "apple", "banana")
my_string = "Hello World"

print(my_list)
print(my_tuple)
print(my_string)

my_list = [1, 2, 3, "apple", "banana"]

my_list.append(4)
my_list.remove(2)

print(my_list)

my_list = ["JM", 19, False, 3.14]

my_list.append("I")
my_list.append("miss")
my_list.append("you")

my_list.remove("JM")
my_list.remove(19)
my_list.remove(False)
my_list.remove(3.14)

message = "Welcome to CC2"
print(message)

message = list(message)
message[2] = ''
message[4] = ''
message[6] = ''
message = ''.join(message)

print(message)
print(my_list)

a = 5
b = 3

sum_result = a + b
subtraction_result = a - b
multiplication_result = a * b
division_result = a / b
remainder_result = a % b
exponentiation_result = a ** b

print(sum_result)
print(subtraction_result)
print(multiplication_result)
print(division_result)
print(remainder_result)
print(exponentiation_result)

x = 5
y = 3

equals = x == y
not_equals = x != y
greater_than = x > y
less_than = x < y
greater_or_equal = x >= y
less_or_equal = x <= y

print(equals)
print(not_equals)
print(greater_than)
print(less_than)
print(greater_or_equal)
print(less_or_equal)

x = True
y = False

and_result = x and y
or_result = x or y
not_result_x = not x
not_result_y = not y

print(and_result)
print(or_result)
print(not_result_x)
print(not_result_y)

# Search algorithm practice

lst = []
for i in range(1,1001):
    lst.append(i)

target = 220

def binary_search(list,target):
    low = 0
    high = len(list) - 1

    if low > high:
        return f"{target} is not in the list."

    mid_index = (high - low) // 2
    mid_value = list[mid_index]

    if mid_value == target:
        return f"{target} is in the list!"
    elif target > mid_value:
        new_list = list[mid_index+1:high+1]
        return binary_search(new_list,target)
    else:
        new_list = list[low:mid_index]
        return binary_search(new_list,target)

result = binary_search(lst,target)
print(f"The list contains all integers from {lst[0]} to {lst[-1]} that is sorted in ascending order.")
print(f"And {result}")
